### ISSUE TITLE
Add an instantiatable comparingengine

### ISSUE THREAD

**Issue by Grinderofl** [StevenGilligan/AutoCompare#6]
I can see this library being used in a similar fashion to AutoMapper, but it has a major flaw right now: everything is static. This prevents one from being able to have two different comparison configurations in the same appdomain easily. If there was a way to configure it and derive an IComparingEngine that could be registered with the DI container, that could be then used to inject into constructors, in a similar fashion as AutoMapper could be used with IMappingEngine

**Comment by StevenGilligan** [comment]
I will definitely implement this. As of now, the library is not built with multiple appdomains / multiple threads supported (it should mostly work if you're careful, but it's untested and unsupported)
